### ISSUE TITLE
Tidy unsaved buffer

### ISSUE THREAD

**Issue by Mallinanga** [welovewordpress/SublimePhpTidy#17]
I think it would be a great addition to be able to tidy a php file that hasn't been saved yet.
Now when i try to tidy an unsaved buffer in ST2 i get the following error in console:

`PhpTidy: invoked on file: None
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./php_tidy.py", line 12, in run
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/posixpath.py", line 95, in splitext
    return genericpath._splitext(p, sep, altsep, extsep)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/genericpath.py", line 91, in _splitext
    sepIndex = p.rfind(sep)
AttributeError: 'NoneType' object has no attribute 'rfind'`

**Comment by essenmitsosse** [comment]
I am getting exactly the same error message, the problem is: the file is already saved.

```
PhpTidy: invoked on file: None
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./php_tidy.py", line 12, in run
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/posixpath.py", line 95, in splitext
    return genericpath._splitext(p, sep, altsep, extsep)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/genericpath.py", line 91, in _splitext
    sepIndex = p.rfind(sep)
AttributeError: 'NoneType' object has no attribute 'rfind'`
```
