### ISSUE TITLE
Accents in comments make PhpTidy failed

### ISSUE THREAD

**Issue by potsky** [welovewordpress/SublimePhpTidy#28]
Hi !

when accents are in comments, invoking PhpTidy gives these messages in the console :

```
PhpTidy: calling script: /opt/local/bin/php "/Users/potsky/Library/Application Support/Sublime Text 3/Packages/SublimePhpTidy/wp-phptidy.php" replace "/tmp/phptidy-sublime-buffer.php"
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "/Users/potsky/Library/Application Support/Sublime Text 3/Packages/SublimePhpTidy/php_tidy.py", line 73, in run
    newContent = fileHandle.read()
  File "X/encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3592: ordinal not in range(128)
```

**Comment by 18601673727** [comment]
Well, I have the same issue with you.

**Comment by carlos-mora** [comment]
+1 
The problem seems to be the double utf-8 encoding produced by line 49 in php_tidy.py:
bufferContent = self.view.substr(bufferLength).encode('utf-8')
this is unnecesary if the file is (the common situation for me) already utf-8 encoded
